module.exports = function createColors(colors) {
  return {
    name: "Esmerald",
    type: "dark",
    semanticHighlighting: true,
    colors: {
      "actionBar.toggledBackground": colors.azulOscuroSuave8,
      "activityBar.activeBorder": colors.amarilloAdvertencia,
      "activityBar.background": colors.fondoPanelOscuro,
      "activityBar.border": colors.fondoPanelOscuro,
      "activityBar.foreground": colors.azulMedioSuaveTransparente10,
      "activityBar.inactiveForeground": colors.azulMedioSuaveTransparente8,
      "activityBarBadge.background": colors.verdeAcento,
      "activityBarBadge.foreground": colors.azulOscuroVivo2,
      "badge.background": colors.rojoError,
      "badge.foreground": colors.blanco,
      "banner.background": colors.fondoPanelOscuro,
      "banner.foreground": colors.textoSecundario,
      "banner.iconForeground": colors.blanco,
      "breadcrumb.activeSelectionForeground": colors.verdeAcento,
      "breadcrumb.background": colors.fondoPanelOscuro,
      "breadcrumb.focusForeground": colors.verdeAcento,
      "breadcrumb.foreground": colors.azulMedioSuaveTransparente10,
      "breadcrumbPicker.background": colors.fondoPanelOscuro,
      "button.background": colors.verdeAcento,
      "button.border": colors.grisClaroSuaveTransparente,
      "button.foreground": colors.fondoPanelOscuro,
      "button.hoverBackground": colors.azulMedioBrillante6,
      "button.secondaryBackground": colors.grisOscuroSuave4,
      "button.secondaryForeground": colors.grisClaroSuave2,
      "button.secondaryHoverBackground": colors.grisOscuroSuave6,
      "charts.blue": colors.azulMedioBrillante2,
      "charts.foreground": colors.textoSecundario,
      "charts.green": colors.verdeAcento,
      "charts.lines": colors.textoSecundario,
      "charts.orange": colors.verdeMedioBrillante5,
      "charts.purple": colors.violetaMedioBrillante3,
      "charts.red": colors.rojoMedioSuave,
      "charts.yellow": colors.amarilloAdvertencia,
      "chat.slashCommandBackground": colors.azulOscuroSuave7,
      "chat.slashCommandForeground": colors.azulMedioBrillante10,
      "checkbox.background": colors.fondoPanelOscuro,
      "checkbox.border": colors.fondoPanelOscuro,
      "checkbox.foreground": colors.verdeAcento,
      "commandCenter.background": colors.fondoPanelOscuro,
      "commandCenter.foreground": colors.azulMedioSuaveTransparente10,
      "debugExceptionWidget.background": colors.rojoMedioBrillanteTransparente,
      "debugExceptionWidget.border": colors.rojoMedioBrillanteTransparente,
      "debugIcon.breakpointCurrentStackframeForeground":
        colors.naranjaMedioBrillanteTransparente6,
      "debugIcon.breakpointDisabledForeground":
        colors.rojoMedioBrillanteTransparente,
      "debugIcon.breakpointForeground": colors.rojoError,
      "debugIcon.breakpointStackframeForeground":
        colors.azulMedioBrillanteTransparente2,
      "debugIcon.breakpointUnverifiedForeground": colors.textoSecundario,
      "debugIcon.continueForeground": colors.verdeAcento,
      "debugIcon.disconnectForeground": colors.rojoError,
      "debugIcon.pauseForeground": colors.verdeAcento,
      "debugIcon.restartForeground": colors.amarilloAdvertencia,
      "debugIcon.startForeground": colors.verdeAcento,
      "debugIcon.stepBackForeground": colors.textoSecundario,
      "debugIcon.stepIntoForeground": colors.textoSecundario,
      "debugIcon.stepOutForeground": colors.textoSecundario,
      "debugIcon.stepOverForeground": colors.textoSecundario,
      "debugIcon.stopForeground": colors.rojoError,
      "debugToolBar.background": colors.azulOscuroVivo2,
      "debugToolBar.border": colors.azulOscuroVivo2,
      descriptionForeground: colors.textoSecundario,
      "dropdown.background": colors.fondoPanelOscuro,
      "dropdown.border": colors.grisOscuroSuave6,
      "dropdown.foreground": colors.textoSecundario,
      "dropdown.listBackground": colors.fondoPanelOscuro,
      "editor.background": colors.fondoEditorOscuro,
      "editor.findMatchBackground": colors.azulMedioSuaveTransparente5,
      "editor.findMatchHighlightBackground": colors.azulMedioSuaveTransparente7,
      "editor.findRangeHighlightBackground": colors.azulMedioSuaveTransparente7,
      "editor.foldBackground": colors.azulOscuroVivoTransparente,
      "editor.foreground": colors.textoSecundario,
      "editor.inactiveSelectionBackground": colors.grisOscuroSuaveTransparente3,
      "editor.lineHighlightBackground": colors.azulOscuroVivo2,
      "editor.lineHighlightBorder": colors.azulOscuroVivo2,
      "editor.rangeHighlightBackground": colors.azulOscuroSuaveTransparente5,
      "editor.selectionBackground": colors.azulMedioSuaveTransparente4,
      "editor.selectionForeground": colors.fondoPanelOscuro,
      "editor.selectionHighlightBackground": colors.azulMedioSuaveTransparente4,
      "editor.stackFrameHighlightBackground":
        colors.azulMedioSuaveTransparente4,
      "editorBracketHighlight.foreground1": colors.turquesaMedioBrillante,
      "editorBracketHighlight.foreground2": colors.naranjaClaroBrillante2,
      "editorBracketHighlight.foreground3": colors.rojoClaroBrillante3,
      "editorBracketHighlight.foreground4": colors.verdeMedioBrillante7,
      "editorBracketHighlight.unexpectedBracket.foreground": colors.blanco,
      "editorBracketMatch.border": colors.azulOscuroSuave5,
      "editorCursor.background": colors.verdeAcento,
      "editorCursor.foreground": colors.verdeAcento,
      "editorGroup.border": colors.azulOscuroSuave5,
      "editorGroup.dropBackground": colors.azulMedioSuaveTransparente,
      "editorGroupHeader.border": colors.fondoPanelOscuro,
      "editorGroupHeader.tabsBackground": colors.fondoPanelOscuro,
      "editorGroupHeader.tabsBorder": colors.fondoPanelOscuro,
      "editorGutter.addedBackground": colors.verdeMedioBrillanteTransparente11,
      "editorGutter.background": colors.fondoEditorOscuro,
      "editorGutter.commentRangeForeground": colors.textoSecundario,
      "editorGutter.deletedBackground": colors.rojoMedioBrillanteTransparente3,
      "editorGutter.modifiedBackground": colors.azulMedioBrillanteTransparente6,
      "editorHoverWidget.background": colors.azulOscuroVivo2,
      "editorHoverWidget.foreground": colors.textoSecundario,
      "editorIndentGuide.activeBackground1":
        colors.verdeMedioBrillanteTransparente,
      "editorIndentGuide.background1": colors.fondoPanelOscuro,
      "editorInlayHint.background": colors.fondoEditorOscuro,
      "editorInlayHint.foreground": colors.azulMedioVivo8,
      "editorLightBulb.foreground": colors.amarilloAdvertencia,
      "editorLightBulbAutoFix.foreground": colors.verdeAcento,
      "editorLineNumber.activeForeground": colors.textoSecundario,
      "editorLineNumber.foreground": colors.azulOscuroSuave5,
      "editorOverviewRuler.border": colors.azulOscuroBrillante2,
      "editorOverviewRuler.bracketMatchForeground": colors.textoSecundario,
      "editorOverviewRuler.commonContentForeground": colors.verdeAcento,
      "editorOverviewRuler.errorForeground": colors.rojoError,
      "editorOverviewRuler.findMatchForeground":
        colors.azulMedioBrillanteTransparente7,
      "editorOverviewRuler.infoForeground": colors.blanco,
      "editorOverviewRuler.rangeHighlightForeground":
        colors.azulMedioBrillanteTransparente7,
      "editorOverviewRuler.selectionHighlightForeground":
        colors.azulMedioBrillanteTransparente7,
      "editorOverviewRuler.warningForeground": colors.amarilloAdvertencia,
      "editorOverviewRuler.wordHighlightForeground":
        colors.azulMedioSuaveTransparente11,
      "editorRuler.foreground": colors.azulOscuroVivoTransparente4,
      "editorStickyScroll.background": colors.fondoPanelOscuro,
      "editorStickyScroll.shadow": colors.verdeMedioBrillanteTransparente9,
      "editorStickyScrollHover.background":
        colors.verdeMedioBrillanteTransparente7,
      "editorSuggestWidget.background": colors.azulOscuroVivo2,
      "editorSuggestWidget.border": colors.azulOscuroVivo2,
      "editorSuggestWidget.foreground": colors.textoSecundario,
      "editorWidget.background": colors.azulOscuroSuave,
      "editorWidget.border": colors.azulOscuroVivo2,
      errorForeground: colors.rojoError,
      "extensionBadge.remoteBackground": colors.verdeMedioBrillante5,
      "extensionBadge.remoteForeground": colors.fondoPanelOscuro,
      "extensionButton.prominentBackground": colors.verdeAcento,
      "extensionButton.prominentForeground": colors.fondoPanelOscuro,
      "extensionButton.prominentHoverBackground": colors.verdeMedioBrillante8,
      "extensionIcon.starForeground": colors.naranjaMedioBrillanteTransparente3,
      focusBorder: colors.azulOscuroVivo2,
      foreground: colors.textoSecundario,
      "gitDecoration.addedResourceForeground": colors.verdeAcento,
      "gitDecoration.conflictingResourceForeground": colors.amarilloAdvertencia,
      "gitDecoration.deletedResourceForeground": colors.rojoError,
      "gitDecoration.ignoredResourceForeground":
        colors.azulMedioSuaveTransparente6,
      "gitDecoration.modifiedResourceForeground": colors.blanco,
      "gitDecoration.submoduleResourceForeground": colors.verdeMedioBrillante6,
      "gitDecoration.untrackedResourceForeground": colors.textoSecundario,
      "icon.foreground": colors.blanco,
      "inlineChat.shadow": colors.verdeAcento,
      "input.background": colors.azulOscuroSuave4,
      "input.border": colors.fondoPanelOscuro,
      "input.foreground": colors.blanco,
      "input.placeholderForeground": colors.textoSecundario,
      "inputOption.activeBackground": colors.azulOscuroSuave5,
      "inputOption.activeBorder": colors.azulOscuroSuave5,
      "inputOption.activeForeground": colors.textoSecundario,
      "inputValidation.errorBackground": colors.rojoMedioBrillanteTransparente,
      "inputValidation.errorBorder": colors.rojoMedioBrillanteTransparente,
      "inputValidation.errorForeground": colors.blanco,
      "inputValidation.infoBackground": colors.azulMedioBrillanteTransparente4,
      "inputValidation.infoBorder": colors.azulMedioBrillanteTransparente3,
      "inputValidation.infoForeground": colors.blanco,
      "inputValidation.warningBackground":
        colors.naranjaMedioBrillanteTransparente4,
      "inputValidation.warningBorder":
        colors.naranjaMedioBrillanteTransparente4,
      "inputValidation.warningForeground": colors.blanco,
      "keybindingLabel.background": colors.azulMedioSuaveTransparente3,
      "keybindingLabel.border": colors.azulMedioSuaveTransparente4,
      "keybindingLabel.bottomBorder": colors.azulMedioSuaveTransparente9,
      "keybindingLabel.foreground": colors.textoSecundario,
      "list.activeSelectionBackground": colors.azulOscuroSuave5,
      "list.activeSelectionForeground": colors.blanco,
      "list.activeSelectionIconForeground": colors.blanco,
      "list.dropBackground": colors.azulOscuroSuave5,
      "list.errorForeground": colors.rojoError,
      "list.filterMatchBackground": colors.violetaMedioBrillanteTransparente3,
      "list.focusAndSelectionOutline": colors.verdeAcento,
      "list.focusBackground": colors.azulMedioSuave,
      "list.focusForeground": colors.blanco,
      "list.hoverBackground": colors.azulOscuroSuaveTransparente4,
      "list.inactiveSelectionBackground": colors.azulOscuroSuave5,
      "list.warningForeground": colors.amarilloAdvertencia,
      "listFilterWidget.background": colors.azulOscuroSuave7,
      "listFilterWidget.shadow": colors.verdeAcento,
      "menu.background": colors.fondoPanelOscuro,
      "menu.border": colors.verdeMedioBrillanteTransparente5,
      "menu.foreground": colors.grisClaroSuave4,
      "menu.separatorBackground": colors.verdeMedioBrillanteTransparente4,
      "menubar.selectionBackground": colors.verdeAcento,
      "menubar.selectionForeground": colors.fondoEditorOscuro,
      "merge.commonContentBackground": colors.grisClaroSuaveTransparente2,
      "merge.commonHeaderBackground": colors.grisClaroSuaveTransparente2,
      "merge.currentContentBackground": colors.rojoMedioBrillanteTransparente,
      "merge.currentHeaderBackground": colors.rojoMedioBrillanteTransparente3,
      "merge.incomingContentBackground": colors.azulMedioBrillanteTransparente,
      "merge.incomingHeaderBackground": colors.azulMedioBrillanteTransparente5,
      "minimap.background": colors.fondoEditorOscuro,
      "minimap.errorHighlight": colors.rojoMedioBrillanteTransparente5,
      "minimap.findMatchHighlight": colors.verdeMedioBrillanteTransparente12,
      "minimap.foregroundOpacity": colors.azulOscuroBrillanteTransparente,
      "minimap.selectionHighlight": colors.azulMedioBrillanteTransparente8,
      "minimap.warningHighlight": colors.naranjaMedioBrillanteTransparente7,
      "minimapGutter.addedBackground": colors.verdeMedioBrillanteTransparente11,
      "minimapGutter.deletedBackground": colors.rojoMedioBrillanteTransparente3,
      "minimapGutter.modifiedBackground":
        colors.azulMedioBrillanteTransparente6,
      "minimapSlider.activeBackground": colors.azulOscuroVivoTransparente4,
      "minimapSlider.background": colors.azulOscuroVivoTransparente3,
      "minimapSlider.hoverBackground": colors.azulOscuroVivoTransparente3,
      "notificationCenterHeader.background": colors.azulOscuroVivo2,
      "notificationCenterHeader.foreground": colors.grisClaroSuave2,
      "notificationLink.foreground": colors.azulMedioBrillante13,
      "notifications.background": colors.azulOscuroVivo2,
      "notifications.border": colors.grisOscuroSuave3,
      "notifications.foreground": colors.textoSecundario,
      "notificationsErrorIcon.foreground": colors.rojoClaroBrillante3,
      "notificationsInfoIcon.foreground": colors.verdeAcento,
      "notificationsWarningIcon.foreground": colors.naranjaMedioBrillante9,
      "panel.background": colors.fondoPanelOscuro,
      "panel.border": colors.fondoPanelOscuro,
      "panelInput.border": colors.grisOscuroSuave3,
      "panelStickyScroll.shadow": colors.verdeMedioBrillanteTransparente8,
      "panelTitle.activeBorder": colors.amarilloAdvertencia,
      "panelTitle.activeForeground": colors.grisClaroSuave2,
      "panelTitle.inactiveForeground": colors.azulMedioSuave7,
      "peekView.border": colors.azulOscuroVivo2,
      "peekViewEditor.background": colors.fondoPanelOscuro,
      "peekViewEditor.matchHighlightBackground":
        colors.naranjaMedioBrillanteTransparente,
      "peekViewResult.background": colors.grisOscuroSuave,
      "peekViewResult.matchHighlightBackground":
        colors.naranjaMedioBrillanteTransparente,
      "pickerGroup.border": colors.grisOscuroSuave6,
      "ports.iconRunningProcessForeground": colors.verdeMedioVivo2,
      "progressBar.background": colors.verdeAcento,
      "quickInput.background": colors.azulOscuroVivo,
      "quickInput.foreground": colors.grisClaroSuave2,
      "scrollbar.shadow": colors.verdeMedioBrillanteTransparente8,
      "scrollbarSlider.activeBackground":
        colors.verdeMedioBrillanteTransparente10,
      "scrollbarSlider.background": colors.azulMedioSuaveTransparente2,
      "scrollbarSlider.hoverBackground": colors.azulMedioSuaveTransparente4,
      "selection.background": colors.azulClaroVivoTransparente2,
      "settings.checkboxBackground": colors.fondoPanelOscuro,
      "settings.checkboxBorder": colors.azulOscuroVivo3,
      "settings.checkboxForeground": colors.verdeAcento,
      "settings.dropdownBackground": colors.fondoPanelOscuro,
      "settings.dropdownBorder": colors.azulOscuroVivo3,
      "settings.dropdownForeground": colors.textoSecundario,
      "settings.dropdownListBorder": colors.fondoPanelOscuro,
      "settings.headerForeground": colors.blanco,
      "settings.modifiedItemIndicator": colors.verdeAcento,
      "settings.numberInputBackground": colors.fondoPanelOscuro,
      "settings.numberInputBorder": colors.azulOscuroVivo3,
      "settings.numberInputForeground": colors.textoSecundario,
      "settings.textInputBackground": colors.fondoPanelOscuro,
      "settings.textInputBorder": colors.azulOscuroVivo3,
      "settings.textInputForeground": colors.textoSecundario,
      "sideBar.background": colors.fondoPanelOscuro,
      "sideBar.border": colors.fondoPanelOscuro,
      "sideBar.foreground": colors.textoSecundario,
      "sideBarSectionHeader.background": colors.fondoPanelOscuro,
      "sideBarSectionHeader.border": colors.grisMedioSuaveTransparente2,
      "sideBarSectionHeader.foreground": colors.grisClaroSuave2,
      "sideBarTitle.foreground": colors.amarilloAdvertencia,
      "statusBar.background": colors.azulOscuroVivo2,
      "statusBar.border": colors.azulOscuroVivo2,
      "statusBar.debuggingBackground": colors.azulOscuroBrillanteTransparente,
      "statusBar.debuggingForeground": colors.turquesaClaroBrillante,
      "statusBar.focusBorder": colors.azulMedioBrillante4,
      "statusBar.foreground": colors.textoSecundario,
      "statusBar.noFolderBackground": colors.azulOscuroVivo2,
      "statusBar.noFolderForeground": colors.textoSecundario,
      "statusBarItem.focusBorder": colors.azulMedioBrillante4,
      "statusBarItem.prominentBackground": colors.grisMedioSuaveTransparente2,
      "statusBarItem.remoteBackground": colors.azulOscuroVivo2,
      "statusBarItem.remoteForeground": colors.blanco,
      "tab.activeBackground": colors.azulOscuroSuave3,
      "tab.activeBorder": colors.fondoPanelOscuro,
      "tab.activeBorderTop": colors.fondoPanelOscuro,
      "tab.activeForeground": colors.textoSecundario,
      "tab.activeModifiedBorder": colors.textoSecundario,
      "tab.border": colors.fondoPanelOscuro,
      "tab.hoverBackground": colors.azulMedioSuave,
      "tab.hoverBorder": colors.fondoPanelOscuro,
      "tab.inactiveBackground": colors.fondoPanelOscuro,
      "tab.inactiveForeground": colors.azulMedioSuaveTransparente10,
      "tab.lastPinnedBorder": colors.azulMedioSuaveTransparente4,
      "tab.unfocusedActiveBorder": colors.textoSecundario,
      "terminal.ansiBlue": colors.azulMedioBrillante2,
      "terminal.ansiBrightBlue": colors.azulMedioBrillanteTransparente9,
      "terminal.ansiBrightCyan": colors.verdeMedioBrillanteTransparente6,
      "terminal.ansiBrightGreen": colors.verdeMedioBrillanteTransparente13,
      "terminal.ansiBrightMagenta": colors.violetaMedioVivoTransparente,
      "terminal.ansiBrightRed": colors.rojoClaroBrillanteTransparente,
      "terminal.ansiBrightWhite": colors.grisMedioSuave2,
      "terminal.ansiBrightYellow": colors.naranjaMedioBrillante5,
      "terminal.ansiCyan": colors.turquesaMedioVivo3,
      "terminal.ansiGreen": colors.verdeMedioVivo3,
      "terminal.ansiMagenta": colors.violetaMedioVivo2,
      "terminal.ansiRed": colors.rojoMedioBrillante,
      "terminal.ansiWhite": colors.grisClaroSuave4,
      "terminal.ansiYellow": colors.naranjaMedioVivo5,
      "terminal.background": colors.fondoPanelOscuro,
      "terminal.foreground": colors.textoSecundario,
      "terminal.inactiveSelectionBackground": colors.grisOscuroSuave5,
      "terminal.tab.activeBorder": colors.azulMedioBrillante4,
      "terminalCursor.background": colors.azulOscuroSuave5,
      "terminalCursor.foreground": colors.verdeAcento,
      "testing.iconErrored": colors.amarilloAdvertencia,
      "testing.iconFailed": colors.rojoError,
      "testing.iconPassed": colors.verdeAcento,
      "testing.iconQueued": colors.textoSecundario,
      "testing.iconSkipped": colors.textoSecundario,
      "testing.iconUnset": colors.textoSecundario,
      "testing.message.error.lineBackground": colors.rojoError,
      "testing.message.info.decorationForeground": colors.azulMedioBrillante2,
      "testing.message.info.lineBackground": colors.azulMedioBrillante2,
      "testing.peekBorder": colors.textoSecundario,
      "textBlockQuote.background": colors.fondoPanelOscuro,
      "textBlockQuote.border": colors.textoSecundario,
      "textCodeBlock.background": colors.fondoPanelOscuro,
      "textLink.activeForeground": colors.verdeMedioBrillante8,
      "textLink.foreground": colors.verdeAcento,
      "textPreformat.background": colors.azulOscuroVivoTransparente2,
      "textPreformat.foreground": colors.amarilloClaroBrillante,
      "textSeparator.foreground": colors.blanco,
      "titleBar.activeBackground": colors.fondoPanelOscuro,
      "titleBar.activeForeground": colors.azulMedioSuaveTransparente10,
      "titleBar.border": colors.fondoPanelOscuro,
      "titleBar.inactiveBackground": colors.fondoPanelOscuro,
      "titleBar.inactiveForeground": colors.azulMedioSuaveTransparente10,
      "tree.indentGuidesStroke": colors.verdeAcento,
      "walkThrough.embeddedEditorBackground": colors.fondoPanelOscuro,
      "welcomePage.background": colors.fondoPanelOscuro,
      "welcomePage.progress.foreground": colors.azulMedioBrillante4,
      "welcomePage.tileBackground": colors.grisOscuroSuave3,
      "widget.border": colors.verdeAcento,
      "widget.shadow": colors.verdeMedioBrillanteTransparente8,
      "window.activeBorder": colors.azulOscuroVivo2,
    },
  };
};
